---
title: "brian-kelly-margin-of-victory-prediction"
author: "Justin Shotwell"
date: "April 4, 2020"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggthemes)
library(lubridate)
theme_set(theme_tufte())

nd_fb_games <- read_csv("notre_dame_football_game_history.csv") %>%
  mutate(mov = nd_score - opp_score,
         date = mdy(date),
         month = as_factor(month),
         nd_rank = as_factor(replace_na(nd_rank, "NR")),
         opp_rank = as_factor(replace_na(opp_rank, "NR")))
         
nd_fb_games$nd_rank <- fct_relevel(nd_fb_games$nd_rank, levels = "1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","NR")

nd_fb_games$opp_rank <- fct_relevel(nd_fb_games$opp_rank, levels = "1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","NR")

nd_fb_games$month <- fct_relevel(nd_fb_games$month, levels = "8","9","10","11","12","1")

```

```{r}

brian_kelly <- nd_fb_games %>%
  filter(head_coach == "Brian Kelly")

```

```{r}

brian_kelly %>%
  ggplot(aes(site, mov, color = site), legend("none")) +
  geom_jitter(alpha = 0.5, width = 0.1) +
  theme(legend.position = "none") +
  geom_hline(yintercept = 0) +
  labs(x = "Site",
       y = "Margin of Victory",
       title = "Margin of Victory Based on Site")

```

```{r}

brian_kelly %>%
  ggplot(aes(nd_rank, mov)) +
  geom_jitter(alpha = 0.5, width = 0.1) +
  theme(legend.position = "none") +
  geom_hline(yintercept = 0) +
  labs(x = "Notre Dame's Rank",
       y = "Margin of Victory",
       title = "Margin of Victory Based on Notre Dame Rank")

```

```{r}

brian_kelly %>%
  ggplot(aes(opp_rank, mov)) +
  geom_jitter(alpha = 0.5, width = 0.1) +
  theme(legend.position = "none") +
  geom_hline(yintercept = 0) +
  labs(x = "Notre Dame's Opponent Rank",
       y = "Margin of Victory",
       title = "Margin of Victory Based on Notre Dame's Opponent Rank")

```

```{r}

brian_kelly %>%
  ggplot(aes(month, mov)) +
  geom_jitter(alpha = 0.5, width = 0.1) +
  theme(legend.position = "none") +
  geom_hline(yintercept = 0)

```

